"""add status and is_active to enquiries

Revision ID: 224433675cc5
Revises: 6c0ae5301782
Create Date: 2026-04-11 21:16:27.813304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224433675cc5'
down_revision: Union[str, Sequence[str], None] = '6c0ae5301782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('status', sa.String(), nullable=True))
    op.add_column('enquiries', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('enquiries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'updated_at')
    op.drop_column('enquiries', 'is_active')
    op.drop_column('enquiries', 'status')
    # ### end Alembic commands ###
