"""add admin_notes to enquiries

Revision ID: 60400129636a
Revises: 224433675cc5
Create Date: 2026-04-11 21:40:11.552395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60400129636a'
down_revision: Union[str, Sequence[str], None] = '224433675cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('admin_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'admin_notes')
    # ### end Alembic commands ###
