"""add many-to-many booking system

Revision ID: 6c0ae5301782
Revises: 743f6836b308
Create Date: 2026-04-08 00:02:52.383277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0ae5301782'
down_revision: Union[str, Sequence[str], None] = '743f6836b308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('event_date_time', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('budget_offered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_bookings_id'), 'program_bookings', ['id'], unique=False)
    op.create_foreign_key(None, 'booking_courses', 'program_bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_courses', type_='foreignkey')
    op.drop_index(op.f('ix_program_bookings_id'), table_name='program_bookings')
    op.drop_table('program_bookings')
    # ### end Alembic commands ###
