"""initial migration

Revision ID: 905986d3baff
Revises: 
Create Date: 2026-03-30 14:29:59.605272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905986d3baff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('courses', 'image_url')
    op.drop_column('courses', 'is_active')
    op.drop_column('courses', 'fee')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
